updated node-runner docs with CORE_SECURE_RANDOM_SOURCE
radixdlt/docs pull request #1
Opened 2019-03-07 08:41 UTC by blenessy

2019-03-18 16:35 UTC, blenessy commented
@bucanero Any chance that this can be merged soon ?

2019-03-18 19:29 UTC, bucanero requested changes
Hi Zalan, here's my review

2019-03-18 19:29 UTC, bucanero commented on node-runners/start/README.md
> +### CORE\_SECURE\_RANDOM\_SOURCE <a id="core_secure_random_source"></a>
to match the rest of the items in the section, add another '#' (so it's '####' ) like:
#### CORE\_SECURE\_RANDOM\_SOURCE

2019-03-18 19:29 UTC, bucanero commented on node-runners/start/README.md
> +However, power users might want to switch to `/dev/random`, in which case a decent a entropy generator side-car container
remove an 'a', in this line; changed to "... in which case a decent entropy generator ..."

2019-03-18 19:29 UTC, bucanero commented on node-runners/start/README.md
> +**NOTE**: Switching to `/dev/random` without an decent entropy generator might cause unexpected periodical stalls (hanging).
change 'an' to 'a':  "... without a decent entropy generator..."

2019-03-21 11:32 UTC, blenessy commented
Thanks for your comments @bucanero . I fixed the comments can we please merge this ?

2019-03-21 12:53 UTC, merged

2019-03-21 12:57 UTC, bucanero commented
Reviewed and merged.